  
Resources:
  myNestedEC2LaunchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        https://shunmuga-cf-stacks-07-august-2022.s3.amazonaws.com/nested-stack-single-ec2-launch.yaml
         
  MyParentEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: "MyParentEC2Instance-1"
