  
Resources:
  myNestedEC2WithSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        https://shunmuga-cf-stacks-07-august-2022.s3.amazonaws.com/nested-stack-ec2-security-group-params.yaml
      Parameters:
        SSHSecurityGroupDescription: "SSH 22 - supplied by parent stack"
        HTTPSecurityGroupDescription: "HTTP 80 - supplied by parent stack"
        MyNestedEC2InstanceName: "NestedEC2 Instance - Parent Stack"
                
      
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating a S3 bucket from CloudFormation
    Properties:
      BucketName: !GetAtt myNestedEC2WithSecurityGroupStack.Outputs.MyNestedEC2InstanceID
      VersioningConfiguration:
        Status: Enabled


Outputs:
  MyS3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref MyS3Bucket
  MyS3BucketArn:
    Description: ARN for the new bucket.
    Value: !GetAtt MyS3Bucket.Arn 